# Generated by Django 5.1.1 on 2024-10-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_autopark'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep'), ('Wagon', 'Wagon')], default='Wagon', max_length=9),
            preserve_default=False,
        ),
    ]
